source 'https://rubygems.org'

gem 'rails', '4.2.0'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'

gem 'slim'

gem 'mongoid'

gem 'dragonfly'
gem 'dragonfly-mongoid_data_store'

gem 'simple_form_attachments', path: '../../../simple_form_attachments'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
